name: Publish

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.ref }}

jobs:
  publish_android:
    name: Publish Android
    if: ${{ github.repository_owner == 'shensven' }}

    runs-on: ubuntu-latest

    steps:
      - name: Checkout git repository
        uses: actions/checkout@v3

      - name: Install Azul JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 11

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Cache yarn dependencies
        uses: actions/cache@v3
        id: yarn-cache
        with:
          path: |
            node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Cache gradle dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/android/*.gradle', '**/android/*.properties', '**/android/gradle/wrapper/gradle-wrapper.properties', '**/android/app/*.gradle') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Get app version
        id: app_version
        run: |
          APP_VERSION=$(node -e "console.log(require('./package.json').version)")
          echo ::set-output name=app_version::$APP_VERSION

      - name: Install dependencies
        run: |
          yarn install --frozen-lockfile

      - name: Release
        env:
          VERSION_CODE: ${{ github.run_number }}
          VERSION_NAME: ${{ steps.app_version.outputs.app_version }}
        run: |
          cd android && chmod +x gradlew
          ./gradlew assembleRelease
          ./gradlew bundleRelease

      - name: Upload apk
        uses: ncipollo/release-action@v1.10.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          name: v${{ steps.app_version.outputs.app_version }}
          tag: v${{ steps.app_version.outputs.app_version }}
          allowUpdates: true
          draft: true
          artifacts: 'android/app/build/outputs/apk/release/*.*'

      - name: Upload aab
        uses: ncipollo/release-action@v1.10.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          name: play-store
          tag: play-store
          allowUpdates: true
          draft: true
          artifacts: 'android/app/build/outputs/bundle/release/*.*'
